name: Deploy Pifou

on:
  push:
    branches: [test]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:
    environment:
      name: github-pages
    env:
      PUBLIC_WP_PASSWORD: ${{vars.PUBLIC_WP_PASSWORD}}
      THE_TEST: ${{secrets.THE_TEST}}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Print name
        run: echo "Hello $THE_TEST . My PW is $PUBLIC_WP_PASSWORD"
