name: Deploy Pifou

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:
    env:
      GLOP: 'glop'
      THE_TEST: ${{secrets.THE_TEST}}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Print name
        run: echo "Hello. My API_KEY is $THE_TEST"
